### PR TITLE
Styling margin directive from sphinx-book-theme

### PR DESCRIPTION
**Pull request by AakashGfude**
Desktop :  
 
Screen Shot 2023-11-07 at 11 58 22 am

Mobile:

Screen Shot 2023-11-07 at 11 56 03 am

TODO:

  

- [x]  interaction with right sidebar toc
- [x] Add docs

fixes https://github.com/QuantEcon/quantecon-book-theme/issues/229

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude this is looking nice. 

does the `margin` note need to have a title (or is that optional?)

**Comment by AakashGfude** [comment]
@mmcky, that is optional, but it currently has a fixed title space. The style coming from Pydata:

Screen Shot 2023-11-10 at 10 57 20 am


**Unlike that in sbt:**

Screen Shot 2023-11-10 at 11 07 11 am

I will fix it.

**Comment by AakashGfude** [comment]
@mmcky I have done this here, for margins without title:

Screen Shot 2023-11-10 at 1 24 21 pm

**Comment by mmcky** [comment]
thanks @AakashGfude happy for your to go ahead and merge when you're ready. 

can you add that this is supported to the docs as well

**Comment by AakashGfude** [comment]
@mmcky, this has been added to the docs. What do you think?
Screen Shot 2023-11-14 at 10 52 31 am

**Comment by AakashGfude** [comment]
@mmcky I have also cleaned the design a bit, mimicking the sphinx-book-theme now:

Screen Shot 2023-11-14 at 2 49 10 pm


Responsive:

Screen Shot 2023-11-14 at 3 01 40 pm

What do you think?

There are a few additional changes/additions for margin content:

- [ ] handling the tag `figclass: margin-caption` for making figure captions behave as margins. 
- [ ] making margins responsive (handling for phone screens).
- [ ] styling notes code blocks for margins.

**Comment by mmcky** [comment]
thanks @AakashGfude this is looking nice -- much better. 

Last question -- what happens on the `latex` side of things for margin notes?

**Review by mmcky — APPROVED** [review]

**Comment by AakashGfude** [comment]
@mmcky, I have this planned this week—the latex thing. The latex build was failing in my system, so I could not test it immediately. I will correct that first.

**Comment by AakashGfude** [comment]
@mmcky for latex build, the margin is looking like this:- 
Screen Shot 2023-12-12 at 4 38 57 pm

What do you think is the best UI for margins? Given they cant hang on the side like websites. Let me check jupyter book as well

**Comment by mmcky** [comment]
thanks @AakashGfude if they don't break `LaTeX` builds that is great news. 

That means we can deploy this theme update without potential lack of support on the `pdf` side causing build failures. 

Of course it would be good to add support for it over time to `sphinx-jupyterbook-latex`

Perhaps next steps are:

1. Open an Issue in `sphinx-jupyterbook-latex` to make improvements to `margin` object support in `pdf`
2. I think this is probably the most common practice in terms of `TeX` support https://www.overleaf.com/learn/latex/Margin_notes

**Comment by AakashGfude** [comment]
That sounds excellent @mmcky. Thanks, I will do that.

**Pull request merged**
