### PR TITLE
👌 IMPROVE: Adding functionality to handle launch buttons like in datascience lectures.

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR is an attempt to copy the functionality of launch buttons as in https://datascience.quantecon.org/python_fundamentals/control_flow.html#net-present-values-and-asset-pricing , over to qe-theme. 

The present state of functionalities implemented here is a bit underwhelming as I wanted to get ideas on design and approach and reach a common ground. Would love @DrDrij to help me with the UI.

The functionalities at present are:

- `launch_buttons` object structure in config file has not been interfered with, 
  Screen Shot 2021-03-22 at 5 24 31 pm
  but we can use structure ideas mentioned in this thread, like https://github.com/executablebooks/jupyter-book/issues/1253#issuecomment-790742472 . So, that we can also give a good name to the options in the "public" dropdown menu. (which at present has names like `colab_url` etc.)
- UI of the feature is basic with the functionality to select either colab, jupyter_hub, binder server in the dropdown(public), or specify your own in private text input. The server specified in the private text input has been considered to be jupyterhub by default at present. (same as in  datascience theme: https://datascience.quantecon.org/ ). I suppose because binder and colab URLs are always public servers?
- The UI as I said is very basic. 😅 There is no check at present on entries in the `private` input field. 

cc: @jlperla @mmcky @DrDrij  @choldgraf

### CODE REVIEW

**Comment by DrDrij** [comment]
Nice work @AakashGfude . Looking good already. I'll have a think and maybe put together a mockup - and touch base with you.

**Comment by AakashGfude** [comment]
Have added the feature to remove the "settings" dropdown icon, when only one server is specified.

**Comment by mmcky** [comment]
Thanks @AakashGfude would you mind adding what this currently looks like (via screenshot) for:

1. single service case
2. multiple service case

Thanks -- then we can check in with @DrDrij this afternoon on the styling.

**Comment by AakashGfude** [comment]
> Thanks @AakashGfude would you mind adding what this currently looks like (via screenshot) for:
> 
> 1. single service case
> 2. multiple service case
> 
> Thanks -- then we can check in with @DrDrij this afternoon on the styling.

@mmcky the one we discussed yesterday? Have already added that.

**Comment by mmcky** [comment]
> > Thanks @AakashGfude would you mind adding what this currently looks like (via screenshot) for:
> > 
> > 1. single service case
> > 2. multiple service case
> > 
> > Thanks -- then we can check in with @DrDrij this afternoon on the styling.
> 
> @mmcky the one we discussed yesterday? Have already added that.

Yeah I can see that from the commit history. I am just looking for screenshots to show @DrDrij what the two outputs look like where one is a button (as is now right?) and then the other has a dropdown selector?

**Comment by AakashGfude** [comment]
> > > Thanks @AakashGfude would you mind adding what this currently looks like (via screenshot) for:
> > > 
> > > 1. single service case
> > > 2. multiple service case
> > > 
> > > Thanks -- then we can check in with @DrDrij this afternoon on the styling.
> > 
> > 
> > @mmcky the one we discussed yesterday? Have already added that.
> 
> Yeah I can see that from the commit history. I am just looking for screenshots to show @DrDrij what the two outputs look like where one is a button (as is now right?) and then the other has a dropdown selector?

Aah ok, Got yaa.

**Comment by AakashGfude** [comment]
In the case of multiple servers:

Screen Shot 2021-04-07 at 3 21 17 pm

In the case of one server:

Screen Shot 2021-04-07 at 3 24 52 pm

**Comment by arnavs** [comment]
@AakashGfude what's the status of this PR? 

I think it's a dependency of https://github.com/QuantEcon/lecture-datascience.myst/pull/66

**Comment by AakashGfude** [comment]
> @AakashGfude what's the status of this PR?
> 
> I think it's a dependency of [QuantEcon/lecture-datascience.myst#66](https://github.com/QuantEcon/lecture-datascience.myst/pull/66)

Right. I will merge this by EOD. and release a version. I am reverting the changes of the merge in data science lectures https://github.com/QuantEcon/lecture-datascience.myst/pull/74

**Pull request merged**
