### PR TITLE
Style search: hide close icon, animate open

### PR DESCRIPTION
**Pull request by DrDrij**
- Hides the overlapping close/clear icon on webkit browsers.
- Animate the opening of the search input field.
- Simplify JS.

If this works well, last step to allow clicking magnify to submit form (and clicking away from search to close input field).

### CODE REVIEW

**Comment by DrDrij** [comment]
@mmcky This PR looks better. Thanks for guidance 🙏

**Comment by DrDrij** [comment]
> @mmcky This PR looks better. Thanks for guidance 🙏

Spoke too soon. I need to build it before commit? Sorry @mmcky

**Comment by DrDrij** [comment]
> > @mmcky This PR looks better. Thanks for guidance 🙏
> 
> Spoke too soon. I need to build it before commit? Sorry @mmcky

Forgot about pre-commit. Finally got there..

**Comment by mmcky** [comment]
Ah @DrDrij sorry with delayed review. Just saw the X and I now see it just needs a re-run for anaconda to setup.

**Comment by mmcky** [comment]
@DrDrij I have upgraded to `python==3.10` now so the sample project build shouldn't fail any more.

**Comment by mmcky** [comment]
@DrDrij in the latest test deployment the search box doesn't seem to show up

https://648130a927ea09080280f196--hungry-lovelace-7d0512.netlify.app/intro.html

any ideas?

**Comment by mmcky** [comment]
@DrDrij if you have time to work on this by tomorrow ~3pm AEST tomorrow I will setup a new release and update our sites :-)

**Comment by DrDrij** [comment]
Updated the search field JS. Tested on Chrome, Safari, Firefox. Please let me know how you go @mmcky

**Comment by mmcky** [comment]
thanks @DrDrij I am going to merge this. It's working nicely on the demo

https://6489b6eacb6e88213e2dc04d--hungry-lovelace-7d0512.netlify.app

The only pickup is that the search icon doesn't work in the `header` on the actual search page but it seems to work on all other pages that I tested.

**Review by mmcky — APPROVED** [review]

**Pull request merged**
