### PR TITLE
MAINT: add download notebook link to be served from _notebooks folder

### PR DESCRIPTION
**Pull request by mmcky**
Notebooks will currently be fetched from `_notebooks` but could be updated to be served from a repository later on.

### CODE REVIEW

**Comment by mmcky** [comment]
This is looking good -- with the links well formed.  I am going to update this to use lecture-python-programming.notebooks so that we can merge this and the links won't be broken on the current site. Then we can add a github action to update lecture-python-programming.notebooks with generated files using `sphinx-tojupyter`

**Comment by mmcky** [comment]
actually that is going to require a `_config.yml` setting for the `github notebook` repository

https://github.com/quantecon/lecture-python-programming.notebooks

**Comment by mmcky** [comment]
@AakashGfude I am going to leave this as downloading notebooks from `_notebooks` rather than use `lecture-python-programming.notebooks` so that the site is self contained. But we will need to issue a release so that I don't break the current website until we merge in https://github.com/QuantEcon/lecture-python-programming.myst/pulls

**Comment by AakashGfude** [comment]
@mmcky , the token should be uploaded now.

**Pull request merged**
