### PR TITLE
Refactoring quantecon-book-theme

### PR DESCRIPTION
**Pull request by AakashGfude**
We are moving from setup.py to pyprojet.toml. Also having `sphinx-theme-builder` as the build system.

Fixes a bug for exercise icons now being rendered correctly

### CODE REVIEW

**Comment by mmcky** [comment]
Thanks @AakashGfude - It looks like this is building nicely and a good refactor of the code to bring it inline with EBP themes.

**Comment by mmcky** [comment]
@AakashGfude does this incorporate any updates to `search` or `dark theme` etc?

**Review by mmcky — APPROVED** [review]

**Review by mmcky — COMMENTED** [review]
@AakashGfude this is looking good. 

I think the main thing left is to:

- [ ] update `README` with instructions on how to setup the package locally and how to publish as well (generating the various `scss` files etc.)

**Comment by AakashGfude** [comment]
Thanks @mmcky for checking this, I will verify the dark theme. I did get some changes in search locally, but in CI it seems to be the same unfortunately, which is quite puzzling. I will target it in another PR? 
I have time tomorrow. So, I will update the README, and verify the dark theme, work a bit on search.

**Comment by AakashGfude** [comment]
@mmcky, this PR should be mergeable now.

**Comment by mmcky** [comment]
thanks @AakashGfude -- exciting.

**Comment by mmcky** [comment]
@AakashGfude I have been testing this against `lecture-python-intro` and it is looking good. No visual differences that I can see with the current site 👍 

For some embedded objects like `sphinx-exercise` there is a missing icon it seems. Is that theme related or `sphinx-exercise` issue?


Screenshot 2023-09-26 at 4 20 10 pm

**Comment by AakashGfude** [comment]
@mmcky thanks for testing it. Looks like a font awesome issue. I will have a look

**Comment by AakashGfude** [comment]
@mmcky it seems like the issue is also there in the current website: https://intro.quantecon.org/inequality.html

**Comment by AakashGfude** [comment]
@mmcky I have made a change in CSS here, using pydata's icon set. 
Screen Shot 2023-09-27 at 11 41 52 pm

Given that the icon is still working in ebp documentation https://ebp-sphinx-exercise.readthedocs.io/en/latest/syntax.html . And most probably a version issue of fontawesome, I thought of correcting it in our theme, which is inheriting from pydata and using a newer fontawesome version.

**Comment by mmcky** [comment]
thanks @AakashGfude are you happy for me to merge this?

**Comment by mmcky** [comment]
Once this is merged would you be able to put a release PR together? 

I think a major release number `0.6.0` would be good.

**Review by mmcky — APPROVED** [review]

**Comment by AakashGfude** [comment]
Thanks @mmcky for reviewing this. Will cut a release.

**Pull request merged**
