### PR TITLE
👌 IMPROVE: Refactoring and upgrading

### PR DESCRIPTION
**Pull request by AakashGfude**
The following PR is a refactor with the following improvements/features

- [x] upgraded to mathjax v3 from v2
- [x] making `interact` feature of ipywidgets work with mathjax
- [x] using web-compile https://github.com/executablebooks/web-compile to minify and hash css, js files. And create theme.conf file
- [x] Adding tox
- [x] reshuffling js files, and making tippy and feather work with it.
- [x] style changes in right navigation menu
- [x] docs update

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude ping me as a reviewer when this is ready for a review.

**Comment by mmcky** [comment]
Adding some test PR's

- [lecture-python.myst] https://github.com/QuantEcon/lecture-python.myst/pull/135

**Comment by mmcky** [comment]
@AakashGfude a number of styles still need to be migrated. 

- [ ] display math needs to be `centered` by default

Screen Shot 2021-05-04 at 1 14 19 pm


- [ ] some `inline` math is not showing correct such as the following in [linear algebra section](https://6090bbb23bd8ca7ac1501795--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#linear-independence)

Screen Shot 2021-05-04 at 1 16 06 pm

**Comment by AakashGfude** [comment]
> * [ ]  some `inline` math is not showing correctly such as the following in [linear algebra section](https://6090bbb23bd8ca7ac1501795--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#linear-independence)

@mmcky , the above point in the netlify link looks fine in chrome, are you in safari?
Screen Shot 2021-05-04 at 1 56 28 pm

**Comment by mmcky** [comment]
> > * [ ]   some `inline` math is not showing correctly such as the following in [linear algebra section](https://6090bbb23bd8ca7ac1501795--nostalgic-wright-5fa355.netlify.app/linear_algebra.html#linear-independence)
> 
> @mmcky , the above point in the netlify link looks fine in chrome, are you in safari?
> Screen Shot 2021-05-04 at 1 56 28 pm

Yeah I am using `safari`

**Comment by mmcky** [comment]
nice work on the `javascript` fix @AakashGfude 

https://6090cb92937c549956e4e108--wonderful-lalande-528d1c.netlify.app/matsuyama.html#interactive-version

I will need to add a note that it isn't connected to a running kernel but this is looking neat.

**Comment by AakashGfude** [comment]
> I will need to add a note that it isn't connected to a running kernel but this is looking neat.
 
true. it is not working for sphinx-book-theme as well. so we might need to target it on the parent package it seems.

**Comment by mmcky** [comment]
@AakashGfude this is looking good on the rebuilds. 

I found one small instance of that incomplete font issue. It looks like it is using `chtml` still as the default. I could only find it in one place but I will keep an eye out for that issue.

You happy to merge this and then update #100 and #93

**Comment by mmcky** [comment]
@AakashGfude this is the case I am finding the issue still with the fonts in `linear algebra` of `lecture-python.myst`

Screen Shot 2021-05-05 at 12 51 18 pm

**Comment by AakashGfude** [comment]
@mmcky merging this one.🚀

**Pull request merged**
