### PR TITLE
✨ NEW: Advanced launch notebook button + popup

### PR DESCRIPTION
**Pull request by DrDrij**
Replicating something similar to the launcher on the current DataScience site.
Simple + advanced launch notebook buttons.

https://user-images.githubusercontent.com/5886045/119298978-6bd7e680-bca1-11eb-9e3b-8b46e5dda305.mov

### CODE REVIEW

**Comment by mmcky** [comment]
@DrDrij looks like the simple click through is working nicely for the programming lecture site 👍

**Review by mmcky — APPROVED** [review]

**Comment by AakashGfude** [comment]
Nice one @DrDrij . Looking wonderful. The only major thing left is to be able to capture the branch name specified in `_config.yml` . 

```
html_theme_options: 
      repository_branch: main
```

and appending it to the jupyterlab URL  constructed from the private input field, by adding `&branch={branch}`

**Comment by mmcky** [comment]
@DrDrij @AakashGfude are we able to finalise this PR and hand over what we have to `datascience`. I am meeting with them tomorrow to discuss how to switch the `datascience` site over to be the new live site. So it would be great to have a timeline on this. Thanks.

**Comment by mmcky** [comment]
@DrDrij can this also be documented (I can help with this) but it would be good to know what the limitations are. (i.e. can you specify multiple jupyterhub sites etc.)

**Comment by mmcky** [comment]
@DrDrij as per https://github.com/QuantEcon/lecture-datascience.myst/pull/83#issuecomment-848445952 this can be renamed "Notebook Launcher" I think.

**Comment by AakashGfude** [comment]
> @DrDrij @AakashGfude are we able to finalise this PR and hand over what we have to `datascience`. 

I think the branch thing is one of the major things remaining. And needed for datascience, as their branch is `main` and not the default we have set `master`. 
I am happy to implement this change today, if @DrDrij is occupied :)

**Comment by mmcky** [comment]
thanks @AakashGfude I think you're right -- this flexibilty will be useful even if for `master`/`main` transitions.

**Comment by AakashGfude** [comment]
I will merge this one to `private-jupyterlab` branch.

**Review by AakashGfude — APPROVED** [review]

**Pull request merged**
