### PR TITLE
Table styling

### PR DESCRIPTION
**Pull request by DrDrij**
This PR make small adjustments to the table styling (#79).
- Match styling of sphinx site
- Remove margin from paragraph elements within cells
- Restore JS wrapping of tables with div for horizontal scrolling on mobile

### CODE REVIEW

**Comment by AakashGfude** [comment]
@DrDrij this looks good. Thanks a lot. 
The only minute difference with the sphinx site is the alignment of integer numbers. 
Screen Shot 2021-04-06 at 2 05 37 pm

The integers('1' in this case for pp) are left-aligned instead of center. 
Personally, I don't mind any alignment , but just bringing it up in case it matters to someone.

**Comment by mmcky** [comment]
thanks @AakashGfude I think left alignment of the numbers looks good. @DrDrij perhaps we can make this change tomorrow and then merge this PR. @AakashGfude if you can make the numbers aligned please go ahead.

**Comment by AakashGfude** [comment]
@mmcky oops sorry, the comment was not clear. It is center aligned in the sphinx site, and left-aligned in this PR. 

In the sphinx site, it looks like this:
Screen Shot 2021-04-06 at 2 11 46 pm

Should have put it in the above comment to compare.

If left-aligned looks better, then we do not need any change in this PR i think.

**Comment by mmcky** [comment]
thanks for clarifying @AakashGfude. Great I will merge this then.

**Pull request merged**
