### PR TITLE
Adding author names in title of the main page

### PR DESCRIPTION
**Pull request by AakashGfude**
Screen Shot 2023-12-11 at 1 57 09 pm

Author names from the description need to be removed from individual repos. 

fixes https://github.com/QuantEcon/quantecon-book-theme/issues/233

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac we are adding the ability to create hyperlinked names as well but let us know what you think of style. 

I think:

- [ ] some additional padding between `title` and `authors`

What do you think about the relative text size?

**Comment by AakashGfude** [comment]
@mmcky  I have added links to the author names. kept it blue, to indicate it is clickable?
https://github.com/QuantEcon/quantecon-book-theme/assets/6542997/1afcb6ef-1bbb-4f0a-ab48-c3f2fbd79248

**Comment by AakashGfude** [comment]
@mmcky  author names with links, i have kept it blue purposefully to indicate its clickable.
https://github.com/QuantEcon/quantecon-book-theme/assets/6542997/d8e53230-30e7-4b9f-834f-46bfb5d46ab1


The config variable for this is:

```
authors:
        - name: Thomas J. Sargent
          url: http://www.tomsargent.com/
        - name: John Stachurski
          url: https://johnstachurski.net/
```

**Comment by AakashGfude** [comment]
Note that this link feature extends to author names displayed in sub-pages as well. But will revert to previous non-clickable titles if the `authors` config is not provided.

**Comment by AakashGfude** [comment]
@mmcky have added the feature now to:

1. if number of elements (names) ==2 use **and**
2. if number of elements (names) > 2 then use **name1, name2, and name3**
3. and nothing for number of elements (names) < 2

**Comment by AakashGfude** [comment]
- [ ]  Added docs

**Comment by mmcky** [comment]
thanks @AakashGfude -- great work.

**Review by mmcky — APPROVED** [review]
@AakashGfude I think the remaining items are:

- [ ] check if no author information is provided then the element is not added to the HTML
- [ ] add `font size` passthrough as a config option

Once that edge case is tested and the font size passthrough is set and added to the docs then LGTM. :-)

**Comment by AakashGfude** [comment]
> @AakashGfude I think the remaining items are:
> 
>     * [ ]  check if no author information is provided then the element is not added to the HTML

@mmcky this should be handled already. If no author dict is provided, then we take the author names from the old `author` key (But it doesn't have hyperlinks). If even that is not available, then the element should be empty.

**Comment by mmcky** [comment]
Thanks @AakashGfude that's great.

**Comment by AakashGfude** [comment]
@mmcky I have created a config for font size. called `author_font_size`. Looking for name ideas.
Should we just use it for the main toc page. or the rest of the pages as well? 
Rest of the page have different header size to front toc page, so the same font size might for authors might not have the same look.

**Comment by mmcky** [comment]
> Should we just use it for the main toc page. or the rest of the pages as well?

I think this should be just for `main` page as it is likely to be bigger than other pages. 
I think the other pages is OK as it is (matching font size to text around it). 

I suspect the other pages are using the author information in `_config.yml`. Is that right? We should add a note to the documentation perhaps. 

If yes, maybe the theme author setting should be

mainpage_author
mainpage_author_fontsize

What do you think about that?

**Comment by AakashGfude** [comment]
@mmcky, I made the other pages also use `authors` with hyperlinks, cause I suspected readers would want that clickable as well? And not having to go to main toc to get the link? What do you think? 
The font size one I agree.

**Comment by mmcky** [comment]
> @mmcky, I made the other pages also use authors with hyperlinks, cause I suspected readers would want that clickable as well? And not having to go to main toc to get the link? What do you think?

@AakashGfude -- Roger that. That makes sense and also becomes a single source of truth. So the way it works is if Author is specified in `_config.yml` then that will get used, but if author is specified in `html_theme_options` that will take priority?

Let's keep the relationship in font size on the other pages (to the surrounding text) and only allow font size changes for the mainpage. ✅

**Review by mmcky — APPROVED** [review]
Love your work on this @AakashGfude. Thanks. 

When you're ready please go ahead and merge and make a new release. 

With new features I think you can do a semi-major release `0.7.0`

**Comment by AakashGfude** [comment]
>So the way it works is if Author is specified in `_config.yml` then that will get used, but if author is specified in `html_theme_options` that will take priority?

That's right @mmcky.

> 
> Let's keep the relationship in font size on the other pages (to the surrounding text) and only allow font size changes for the mainpage. ✅

Done!

Great. I will merge and make a release.

**Pull request merged**
