### PR TITLE
ENH: Adding Search

### PR DESCRIPTION
**Pull request by AakashGfude**
Adding a search button:
Screen Shot 2023-04-30 at 11 35 24 pm

Which expands to a search input on clicking:
Screen Shot 2023-04-30 at 11 35 31 pm

And the search result page:

Screen Shot 2023-04-30 at 11 41 56 pm

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude this is looking great -- I like the simple search icon. 

Some comments and ideas:

- [ ] I think it should be located to the right in the same cluster as the font adjustment, brightness etc.
- [ ] once you click on search I think the field should enlarge to be bigger that the current size and incorporate curved or softened corners

@DrDrij would you mind to give @AakashGfude some help in making this a bit more integrated to the site.

**Comment by mmcky** [comment]
@jstac this PR is adding search and was interested in your ideas as well

The demo page:

https://644f3f4291193548b40d375c--hungry-lovelace-7d0512.netlify.app/intro.html

and a search result

https://644f3f4291193548b40d375c--hungry-lovelace-7d0512.netlify.app/search.html?q=matplotlib

**Comment by AakashGfude** [comment]
@mmcky does this look better? Or a bigger search field?

Screen Shot 2023-05-02 at 4 33 03 pm

**Comment by mmcky** [comment]
@AakashGfude I think that looks nice and a good placement.

**Comment by jstac** [comment]
+1 from me @AakashGfude .  Nice work.

**Comment by mmcky** [comment]
@AakashGfude I am excited to have search on our lectures and I think this is looking pretty good. 

I think we can merge this -- and refine with feedback from @DrDrij. 

Thanks for pushing this forward @AakashGfude

**Review by mmcky — APPROVED** [review]

**Pull request merged**
