### PR TITLE
Move MathJax config into JS file, switch to SVG render

### PR DESCRIPTION
**Pull request by DrDrij**
1) Consolidate JS into a single file
2) Get MathJax to render math as SVG

### CODE REVIEW

**Comment by AakashGfude** [comment]
@DrDrij @mmcky Just remembered that a good solution to force `svg` for math equations is by loading it through the config.

For our case it would be:
```
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
```

we can also force this config in our theme if we always want this value.

**Comment by mmcky** [comment]
thanks @AakashGfude it works nicely

https://github.com/QuantEcon/lecture-python-programming.myst/pull/141

**Comment by AakashGfude** [comment]
Also, I know I had added `$(document).ready`. But, I think we will need to change it to `$(window).on('load')` as some of the CDN scripts are async including the mathjax one. So, sometimes the configuration specified might execute before the script is loaded? What do you think @DrDrij?

**Comment by mmcky** [comment]
OK I have enabled `svg` rendering in the `_config.yml` for the lectures

https://github.com/QuantEcon/lecture-python.myst/pull/137

Do we still want to figure out how to override the default in the theme here so that `_config.yml` isn't required?

**Comment by mmcky** [comment]
@DrDrij @AakashGfude is this still required? Just trying to close things that don't need to be open.

**Comment by DrDrij** [comment]
This can be closed @mmcky thanks :)

**Pull request closed without merging**
