### PR TITLE
👌 IMPROVE: Lhs menubar persistent

### LINKED ISSUE #131: [config-option] Enable the choice of making `LHS` menu bar sticky
There is some preference on `datascience` to have  a sticky menubar. Therefore once open it stays open for navigation?

Can we add this as a configurable option for the theme

### PR DESCRIPTION
**Pull request by DrDrij**
This PR adds a function call if a sidebar status has been set in localStorage. If the sidebar is open, it will stay open across pages and sessions (persistent).
Fixes #131 

A variable check has been added `{% if persistent_sidebar is defined and persistent_sidebar is sameas true %}`. If `true` the sidebar will be persistent. Config entry being: `persistent_sidebar: true`

image

### CODE REVIEW

**Comment by DrDrij** [comment]
Need to add a config option to toggle the persistent sidebar.

**Comment by DrDrij** [comment]
Tested with variable but doesn't seem to be working. I think the Jinja logic looks ok. Have I missed something obvious @AakashGfude ?

**Comment by AakashGfude** [comment]
@DrDrij needed to add the variable in `theme.conf.j2` and use `theme_persistent_sidebar` instead of `persistent_sidebar` as sphinx attaches `theme_` for each HTML theme option variable.

Using it inside:
```
sphinx:
  config:
    html_theme_options:
      persistent_sidebar: true
```

**Review by AakashGfude — APPROVED** [review]

**Comment by DrDrij** [comment]
Thanks @AakashGfude. I think this is ready — however the new variable needs to be added to lecture source config. What would be the best way to proceed/test build here @mmcky?

**Comment by mmcky** [comment]
hey @DrDrij we open a PR on `lecture-python.myst` and mark it as "[TEST] <description>" and update the environment.yml to replace `quantecon-book-theme=0.2.x` with

````
git+https://github.com/quantecon/quantecon-book-theme@lhs-menubar-sticky
````

**Comment by mmcky** [comment]
@DrDrij I linked a test case above for you to look at for the `python.quantecon.org` site. 

@AakashGfude can you document (if it isn't already) how to regenerate the fixtures for @DrDrij  -- I am guessing that is what is causing the `ci` issues?

**Comment by AakashGfude** [comment]
@mmcky the ci issue is caused by codecov which I mentioned yesterday. Getting back to it now,

**Review by mmcky — APPROVED** [review]

**Pull request merged**
