### PR TITLE
Setup layouts and markup

### PR DESCRIPTION
**Pull request by DrDrij**
This PR reorganises and simplifies the theme directory.
The QE theme will be standalone and not extend other themes.
This is the first port over of the markup from the static prototype.
The aim is simplicity whilst utilising the available sphinx blocks to generate layouts.

@mmcky Is there a relatively simple way for me to do a test build with this theme?

### CODE REVIEW

**Comment by DrDrij** [comment]
I'll look into these failing checks.

**Comment by mmcky** [comment]
@DrDrij I will add a preview `ci.yml` for github builds of `lecture-python-programming.myst`?

**Comment by mmcky** [comment]
@AakashGfude can you do some local testing of this branch and write a summary for @DrDrij to do local testing.

**Comment by mmcky** [comment]
@AakashGfude when you have this up and running -- let me know and then I will review. Thanks.

**Comment by AakashGfude** [comment]
@DrDrij let me know how you feel about the latest edits. You may need to write some additional css to overwrite some styles coming from the parent `pydata_sphinx_theme`. Also, do have a look at https://github.com/QuantEcon/quantecon-book-theme/blob/master/quantecon_book_theme/static/quantecon-book-theme.js to see which js might be unnecessary for this theme.

**Comment by mmcky** [comment]
@AakashGfude are there any instructions on how we can use this locally? (i.e. before we release as a package)

**Comment by AakashGfude** [comment]
@mmcky aah yes, we can use it locally for our sites. by using:

 `html_theme = "quantecon_book_theme"`

in `conf.py`, once we install this locally.
Note though that there are a few issues in css, which I wanted to let @DrDrij have a look at first.

**Comment by mmcky** [comment]
hey @AakashGfude and @DrDrij here is the current build of `lecture-python-programming` using this branch. 

https://5f6af32ea45debac8e940a34--epic-agnesi-957267.netlify.app/index_toc.html

**Comment by mmcky** [comment]
@AakashGfude I think inheritance (using `bootstrap`?) might be nice so that new features come down the pipeline from `sphinx-book-theme`. Does this add a lot of complication? 

The things I am thinking of are `click to show` features. In `sphinxcontrib-tomyst` I convert `hide-output` and pass that through to `myst-nb` code cells with tag `hide-output` which uses `sphinx-toggle`. (See first code block in: https://5f6af32ea45debac8e940a34--epic-agnesi-957267.netlify.app/numba.html)

**Comment by mmcky** [comment]
@DrDrij in the preview build (on safari) the `contents` seems to hover and moves down with the page and obstructs text. Doesn't happen on mobile.

**Comment by DrDrij** [comment]
Thanks both for putting this together. I've tweaked a bit and have a few questions.

Is it nesesary to extend `pydata_sphinx_theme`? Can we build from the sphinx theme? This would be ideal as there is a lot of additional files being called in the head and foot at the moment.

@mmcky This doesn't need bootstrap. New things like the toggle you mentioned trickle down eg. this has its own `togglebutton.css`. I'd really recommend if we can avoid relying on an array of inherited and nested stylesheets and script files (including bootstrap). I've written the theme from scratch but it should mean relatively simple and conflict-free addition of new features and modules.

Thoughts? Happy to accommodate either way.

**Comment by DrDrij** [comment]
@AakashGfude Thanks for setting up the test site. I wasn't able to get it running (am I doing something wrong?).

```
➜  base git:(qe-theme) make html
Running Sphinx v2.1.2
making output directory... done

Theme error:
no theme named 'quantecon_book_theme' found (missing theme.conf?)
make: *** [html] Error 2
```

**Comment by AakashGfude** [comment]
> I'd really recommend if we can avoid relying on an array of inherited and nested stylesheets and script files (including bootstrap). I've written the theme from scratch but it should mean relatively simple and conflict-free addition of new features and modules.

@DrDrij I second this too. Mostly the inheritance code I added was to accommodate tests, and to see the extensibility of `pydata_sphinx_theme`. And it did seem bloated, and filled with unnecessary files. Removing them and just adhering to a normal `sphinx` templating system should work good enough for us, I think.

should we give this approach a try and see how it feels? @mmcky . Maybe in a new branch? or maybe not.

**Comment by AakashGfude** [comment]
> @AakashGfude Thanks for setting up the test site. I wasn't able to get it running (am I doing something wrong?).
> 
> ```
> ➜  base git:(qe-theme) make html
> Running Sphinx v2.1.2
> making output directory... done
> 
> Theme error:
> no theme named 'quantecon_book_theme' found (missing theme.conf?)
> make: *** [html] Error 2
> ```

@DrDrij , did the installation of the theme - `python setup.py develop` , happened without errors?

**Comment by mmcky** [comment]
> I'd really recommend if we can avoid relying on an array of inherited and nested stylesheets and script files (including bootstrap).

@DrDrij @AakashGfude This makes sense. I'll let you guys decide this.

**Comment by mmcky** [comment]
hey @AakashGfude and @DrDrij can you let me know when you think this will be ready to merge?

I am happy with a basic implementation which we can add features to.

**Comment by mmcky** [comment]
@AakashGfude and @DrDrij do we need this PR now that #8 is open?

**Comment by AakashGfude** [comment]
@mmcky I think we can close this PR. We can just keep the branch for referencing some of the things, later. like adjustments to tests.

**Pull request closed without merging**
